config/routes.rb
Rails.application.routes.draw do
  resources :books

  root to: 'static_pages#dashboard'

  get :prueba, to: 'books#inicio'
  get :prueba2, to: 'books#prueba2'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]


  def inicio
  end

  def prueba2

  end

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :category)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def dashboard

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.category %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/inicio.html.erb
<p class="texto-rojo">ESTE ES EL BOOKS#INICIO</p>
<div> <%= link_to "Prueba", prueba_path %> </div>
<div> <%= link_to "Prueba2", prueba2_path %> </div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/prueba2.html.erb
<p class="texto-rojo">ESTE ES EL BOOKS#INICIO</p>
<div> <%= link_to "Prueba", prueba_path %> </div>
<div> <%= link_to "Prueba2", prueba2_path %> </div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @book.category %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/_footer.html.erb
<footer class="footer footer-static footer-light navbar-border">
  <p class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2">
      <span class="float-md-left d-block d-md-inline-block">Copyright &copy; 2018 <a class="text-bold-800 grey darken-2" href="https://themeforest.net/user/pixinvent/portfolio?ref=pixinvent"
                                                                                     target="_blank">PIXINVENT </a>, All rights reserved. </span>
    <span class="float-md-right d-block d-md-inline-blockd-none d-lg-block">Hand-crafted & Made with <i class="ft-heart pink"></i></span>
  </p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
  <meta name="description" content="Modern admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities with bitcoin dashboard.">
  <meta name="keywords" content="admin template, modern admin template, dashboard template, flat admin template, responsive admin template, web app, crypto dashboard, bitcoin dashboard">
  <meta name="author" content="PIXINVENT">
  <title>Dashboard eCommerce - Modern Admin - Clean Bootstrap 4 Dashboard HTML Template + Bitcoin Dashboard</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>

  <!--  <link rel="apple-touch-icon" href="../../../app-assets/images/ico/apple-icon-120.png">-->
  <!--  <link rel="shortcut icon" type="image/x-icon" href="../../../app-assets/images/ico/favicon.ico">-->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Quicksand:300,400,500,700"
        rel="stylesheet">
  <link href="https://maxcdn.icons8.com/fonts/line-awesome/1.1/css/line-awesome.min.css"
        rel="stylesheet">

</head>

<body class="vertical-layout vertical-content-menu 2-columns   menu-expanded fixed-navbar"
      data-open="click" data-menu="vertical-content-menu" data-col="2-columns">
<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>

<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/static_pages/_ecommerce_statistics.html.erb
<!-- eCommerce statistic -->
<div class="row">
  <div class="col-xl-3 col-lg-6 col-12">
    <div class="card pull-up">
      <div class="card-content">
        <div class="card-body">
          <div class="media d-flex">
            <div class="media-body text-left">
              <h3 class="info">850</h3>
              <h6>Products Sold</h6>
            </div>
            <div>
              <i class="icon-basket-loaded info font-large-2 float-right"></i>
            </div>
          </div>
          <div class="progress progress-sm mt-1 mb-0 box-shadow-2">
            <div class="progress-bar bg-gradient-x-info" role="progressbar" style="width: 80%"
                 aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-lg-6 col-12">
    <div class="card pull-up">
      <div class="card-content">
        <div class="card-body">
          <div class="media d-flex">
            <div class="media-body text-left">
              <h3 class="warning">$748</h3>
              <h6>Net Profit</h6>
            </div>
            <div>
              <i class="icon-pie-chart warning font-large-2 float-right"></i>
            </div>
          </div>
          <div class="progress progress-sm mt-1 mb-0 box-shadow-2">
            <div class="progress-bar bg-gradient-x-warning" role="progressbar" style="width: 65%"
                 aria-valuenow="65" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-lg-6 col-12">
    <div class="card pull-up">
      <div class="card-content">
        <div class="card-body">
          <div class="media d-flex">
            <div class="media-body text-left">
              <h3 class="success">146</h3>
              <h6>New Customers</h6>
            </div>
            <div>
              <i class="icon-user-follow success font-large-2 float-right"></i>
            </div>
          </div>
          <div class="progress progress-sm mt-1 mb-0 box-shadow-2">
            <div class="progress-bar bg-gradient-x-success" role="progressbar" style="width: 75%"
                 aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-lg-6 col-12">
    <div class="card pull-up">
      <div class="card-content">
        <div class="card-body">
          <div class="media d-flex">
            <div class="media-body text-left">
              <h3 class="danger">99.89 %</h3>
              <h6>Customer Satisfaction</h6>
            </div>
            <div>
              <i class="icon-heart danger font-large-2 float-right"></i>
            </div>
          </div>
          <div class="progress progress-sm mt-1 mb-0 box-shadow-2">
            <div class="progress-bar bg-gradient-x-danger" role="progressbar" style="width: 85%"
                 aria-valuenow="85" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--/ eCommerce statistic -->

app/views/static_pages/_horizontal_timeline.html.erb
<!-- Basic Horizontal Timeline -->
<div class="row match-height">
  <div class="col-xl-4 col-lg-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Basic Card</h4>
      </div>
      <div class="card-content">
        <%= image_tag 'carousel/05.jpg', class: 'img-fluid', alt: 'Card image cap' %>
        <div class="card-body">
          <p class="card-text">Some quick example text to build on the card title and make up
            the bulk of the card's content.</p>
          <a href="#" class="card-link">Card link</a>
          <a href="#" class="card-link">Another link</a>
        </div>
      </div>
      <div class="card-footer border-top-blue-grey border-top-lighten-5 text-muted">
        <span class="float-left">3 hours ago</span>
        <span class="float-right">
                  <a href="#" class="card-link">Read More <i class="fa fa-angle-right"></i></a>
                </span>
      </div>
    </div>
  </div>
  <div class="col-xl-8 col-lg-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Horizontal Timeline</h4>
        <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
        <div class="heading-elements">
          <ul class="list-inline mb-0">
            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="card-content">
        <div class="card-body">
          <div class="card-text">
            <section class="cd-horizontal-timeline">
              <div class="timeline">
                <div class="events-wrapper">
                  <div class="events">
                    <ol>
                      <li><a href="#0" data-date="16/01/2015" class="selected">16 Jan</a></li>
                      <li><a href="#0" data-date="28/02/2015">28 Feb</a></li>
                      <li><a href="#0" data-date="20/04/2015">20 Mar</a></li>
                      <li><a href="#0" data-date="20/05/2015">20 May</a></li>
                      <li><a href="#0" data-date="09/07/2015">09 Jul</a></li>
                      <li><a href="#0" data-date="30/08/2015">30 Aug</a></li>
                      <li><a href="#0" data-date="15/09/2015">15 Sep</a></li>
                    </ol>
                    <span class="filling-line" aria-hidden="true"></span>
                  </div>
                  <!-- .events -->
                </div>
                <!-- .events-wrapper -->
                <ul class="cd-timeline-navigation">
                  <li><a href="#0" class="prev inactive">Prev</a></li>
                  <li><a href="#0" class="next">Next</a></li>
                </ul>
                <!-- .cd-timeline-navigation -->
              </div>
              <!-- .timeline -->
              <div class="events-content">
                <ol>
                  <li class="selected" data-date="16/01/2015">
                    <blockquote class="blockquote border-0">
                      <div class="media">
                        <div class="media-left">
                          <%= image_tag 'portrait/small/avatar-s-5.png', class: 'media-object img-xl mr-1', alt: 'Generic placeholder image' %>
                        </div>
                        <div class="media-body">
                          Sometimes life is going to hit you in the head with a brick. Don't lose faith.
                        </div>
                      </div>
                      <footer class="blockquote-footer text-right">Steve Jobs
                        <cite title="Source Title">Entrepreneur</cite>
                      </footer>
                    </blockquote>
                    <p class="lead mt-2">
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum praesentium officia,
                      fugit recusandae ipsa, quia velit nulla adipisci? Consequuntur
                      aspernatur at.
                    </p>
                  </li>
                  <li data-date="28/02/2015">
                    <blockquote class="blockquote border-0">
                      <div class="media">
                        <div class="media-left">
                          <%= image_tag 'portrait/small/avatar-s-6.png', class: 'media-object img-xl mr-1', alt: 'Generic placeholder image' %>
                        </div>
                        <div class="media-body">
                          Sometimes life is going to hit you in the head with a brick. Don't lose faith.
                        </div>
                      </div>
                      <footer class="blockquote-footer text-right">Steve Jobs
                        <cite title="Source Title">Entrepreneur</cite>
                      </footer>
                    </blockquote>
                    <p class="lead mt-2">
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum praesentium officia,
                      fugit recusandae ipsa, quia velit nulla adipisci? Consequuntur
                      aspernatur at.
                    </p>
                  </li>
                  <li data-date="20/04/2015">
                    <blockquote class="blockquote border-0">
                      <div class="media">
                        <div class="media-left">
                          <%= image_tag 'portrait/small/avatar-s-7.png', class: 'media-object img-xl mr-1', alt: 'Generic placeholder image' %>
                        </div>
                        <div class="media-body">
                          Sometimes life is going to hit you in the head with a brick. Don't lose faith.
                        </div>
                      </div>
                      <footer class="blockquote-footer text-right">Steve Jobs
                        <cite title="Source Title">Entrepreneur</cite>
                      </footer>
                    </blockquote>
                    <p class="lead mt-2">
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum praesentium officia,
                      fugit recusandae ipsa, quia velit nulla adipisci? Consequuntur
                      aspernatur at.
                    </p>
                  </li>
                  <li data-date="20/05/2015">
                    <blockquote class="blockquote border-0">
                      <div class="media">
                        <div class="media-left">
                          <%= image_tag 'portrait/small/avatar-s-8.png', class: 'media-object img-xl mr-1', alt: 'Generic placeholder image' %>
                        </div>
                        <div class="media-body">
                          Sometimes life is going to hit you in the head with a brick. Don't lose faith.
                        </div>
                      </div>
                      <footer class="blockquote-footer text-right">Steve Jobs
                        <cite title="Source Title">Entrepreneur</cite>
                      </footer>
                    </blockquote>
                    <p class="lead mt-2">
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum praesentium officia,
                      fugit recusandae ipsa, quia velit nulla adipisci? Consequuntur
                      aspernatur at.
                    </p>
                  </li>
                  <li data-date="09/07/2015">
                    <blockquote class="blockquote border-0">
                      <div class="media">
                        <div class="media-left">
                          <%= image_tag 'portrait/small/avatar-s-9.png', class: 'media-object img-xl mr-1', alt: 'Generic placeholder image' %>
                        </div>
                        <div class="media-body">
                          Sometimes life is going to hit you in the head with a brick. Don't lose faith.
                        </div>
                      </div>
                      <footer class="blockquote-footer text-right">Steve Jobs
                        <cite title="Source Title">Entrepreneur</cite>
                      </footer>
                    </blockquote>
                    <p class="lead mt-2">
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum praesentium officia,
                      fugit recusandae ipsa, quia velit nulla adipisci? Consequuntur
                      aspernatur at.
                    </p>
                  </li>
                  <li data-date="30/08/2015">
                    <blockquote class="blockquote border-0">
                      <div class="media">
                        <div class="media-left">
                          <%= image_tag 'portrait/small/avatar-s-6.png', class: 'media-object img-xl mr-1', alt: 'Card image cap' %>
                        </div>
                        <div class="media-body">
                          Sometimes life is going to hit you in the head with a brick. Don't lose faith.
                        </div>
                      </div>
                      <footer class="blockquote-footer text-right">Steve Jobs
                        <cite title="Source Title">Entrepreneur</cite>
                      </footer>
                    </blockquote>
                    <p class="lead mt-2">
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum praesentium officia,
                      fugit recusandae ipsa, quia velit nulla adipisci? Consequuntur
                      aspernatur at.
                    </p>
                  </li>
                  <li data-date="15/09/2015">
                    <blockquote class="blockquote border-0">
                      <div class="media">
                        <div class="media-left">
                          <%= image_tag 'portrait/small/avatar-s-7.png', class: 'media-object img-xl mr-1', alt: 'Card image cap' %>
                        </div>
                        <div class="media-body">
                          Sometimes life is going to hit you in the head with a brick. Don't lose faith.
                        </div>
                      </div>
                      <footer class="blockquote-footer text-right">Steve Jobs
                        <cite title="Source Title">Entrepreneur</cite>
                      </footer>
                    </blockquote>
                    <p class="lead mt-2">
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum praesentium officia,
                      fugit recusandae ipsa, quia velit nulla adipisci? Consequuntur
                      aspernatur at.
                    </p>
                  </li>
                </ol>
              </div>
              <!-- .events-content -->
            </section>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--/ Basic Horizontal Timeline -->

app/views/static_pages/_product_sell_info.html.erb
<!-- Products sell and New Orders -->
<div class="row match-height">
  <div class="col-xl-8 col-12" id="ecommerceChartView">
    <div class="card card-shadow">
      <div class="card-header card-header-transparent py-20">
        <div class="btn-group dropdown">
          <a href="#" class="text-body dropdown-toggle blue-grey-700" data-toggle="dropdown">PRODUCTS SALES</a>
          <div class="dropdown-menu animate" role="menu">
            <a class="dropdown-item" href="#" role="menuitem">Sales</a>
            <a class="dropdown-item" href="#" role="menuitem">Total sales</a>
            <a class="dropdown-item" href="#" role="menuitem">profit</a>
          </div>
        </div>
        <ul class="nav nav-pills nav-pills-rounded chart-action float-right btn-group" role="group">
          <li class="nav-item"><a class="active nav-link" data-toggle="tab" href="#scoreLineToDay">Day</a></li>
          <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#scoreLineToWeek">Week</a></li>
          <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#scoreLineToMonth">Month</a></li>
        </ul>
      </div>
      <div class="widget-content tab-content bg-white p-20">
        <div class="ct-chart tab-pane active scoreLineShadow" id="scoreLineToDay"></div>
        <div class="ct-chart tab-pane scoreLineShadow" id="scoreLineToWeek"></div>
        <div class="ct-chart tab-pane scoreLineShadow" id="scoreLineToMonth"></div>
      </div>
    </div>
  </div>
  <div class="col-xl-4 col-lg-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">New Orders</h4>
        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
        <div class="heading-elements">
          <ul class="list-inline mb-0">
            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="card-content">
        <div id="new-orders" class="media-list position-relative">
          <div class="table-responsive">
            <table id="new-orders-table" class="table table-hover table-xl mb-0">
              <thead>
              <tr>
                <th class="border-top-0">Product</th>
                <th class="border-top-0">Customers</th>
                <th class="border-top-0">Total</th>
              </tr>
              </thead>
              <tbody>
              <tr>
                <td class="text-truncate">iPhone X</td>
                <td class="text-truncate p-1">
                  <ul class="list-unstyled users-list m-0">
                    <li data-toggle="tooltip" data-popup="tooltip-custom" data-original-title="John Doe"
                        class="avatar avatar-sm pull-up">
                      <%= image_tag 'portrait/small/avatar-s-19.png', class: 'media-object rounded-circle', alt: 'Avatar' %>
                    </li>
                    <li data-toggle="tooltip" data-popup="tooltip-custom" data-original-title="Katherine Nichols"
                        class="avatar avatar-sm pull-up">
                      <%= image_tag 'portrait/small/avatar-s-18.png', class: 'media-object rounded-circle', alt: 'Avatar' %>
                    </li>
                    <li data-toggle="tooltip" data-popup="tooltip-custom" data-original-title="Joseph Weaver"
                        class="avatar avatar-sm pull-up">
                      <%= image_tag 'portrait/small/avatar-s-17.png', class: 'media-object rounded-circle', alt: 'Avatar' %>
                    </li>
                    <li class="avatar avatar-sm">
                      <span class="badge badge-info">+4 more</span>
                    </li>
                  </ul>
                </td>
                <td class="text-truncate">$8999</td>
              </tr>
              <tr>
                <td class="text-truncate">Pixel 2</td>
                <td class="text-truncate p-1">
                  <ul class="list-unstyled users-list m-0">
                    <li data-toggle="tooltip" data-popup="tooltip-custom" data-original-title="Alice Scott"
                        class="avatar avatar-sm pull-up">
                      <%= image_tag 'portrait/small/avatar-s-16.png', class: 'media-object rounded-circle', alt: 'Avatar' %>
                    </li>
                    <li data-toggle="tooltip" data-popup="tooltip-custom" data-original-title="Charles Miller"
                        class="avatar avatar-sm pull-up">

                      <%= image_tag 'portrait/small/avatar-s-15.png', class: 'media-object rounded-circle', alt: 'Avatar' %>
                    </li>
                  </ul>
                </td>
                <td class="text-truncate">$5550</td>
              </tr>
              <tr>
                <td class="text-truncate">OnePlus</td>
                <td class="text-truncate p-1">
                  <ul class="list-unstyled users-list m-0">
                    <li data-toggle="tooltip" data-popup="tooltip-custom" data-original-title="Christine Ramos"
                        class="avatar avatar-sm pull-up">
                      <%= image_tag 'portrait/small/avatar-s-11.png', class: 'media-object rounded-circle', alt: 'Avatar' %>
                    </li>
                    <li data-toggle="tooltip" data-popup="tooltip-custom" data-original-title="Thomas Brewer"
                        class="avatar avatar-sm pull-up">

                      <%= image_tag 'portrait/small/avatar-s-10.png', class: 'media-object rounded-circle', alt: 'Avatar' %>
                    </li>
                    <li data-toggle="tooltip" data-popup="tooltip-custom" data-original-title="Alice Chapman"
                        class="avatar avatar-sm pull-up">
                      <%= image_tag 'portrait/small/avatar-s-9.png', class: 'media-object rounded-circle', alt: 'Avatar' %>
                    </li>
                    <li class="avatar avatar-sm">
                      <span class="badge badge-info">+3 more</span>
                    </li>
                  </ul>
                </td>
                <td class="text-truncate">$9000</td>
              </tr>
              <tr>
                <td class="text-truncate">Galaxy</td>
                <td class="text-truncate p-1">
                  <ul class="list-unstyled users-list m-0">
                    <li data-toggle="tooltip" data-popup="tooltip-custom" data-original-title="Ryan Schneider"
                        class="avatar avatar-sm pull-up">

                      <%= image_tag 'portrait/small/avatar-s-14.png', class: 'media-object rounded-circle', alt: 'Avatar' %>
                    </li>
                    <li data-toggle="tooltip" data-popup="tooltip-custom" data-original-title="Tiffany Oliver"
                        class="avatar avatar-sm pull-up">

                      <%= image_tag 'portrait/small/avatar-s-13.png', class: 'media-object rounded-circle', alt: 'Avatar' %>
                    </li>
                    <li data-toggle="tooltip" data-popup="tooltip-custom" data-original-title="Joan Reid"
                        class="avatar avatar-sm pull-up">

                      <%= image_tag 'portrait/small/avatar-s-12.png', class: 'media-object rounded-circle', alt: 'Avatar' %>
                    </li>
                  </ul>
                </td>
                <td class="text-truncate">$7500</td>
              </tr>
              <tr>
                <td class="text-truncate">Moto Z2</td>
                <td class="text-truncate p-1">
                  <ul class="list-unstyled users-list m-0">
                    <li data-toggle="tooltip" data-popup="tooltip-custom" data-original-title="Kimberly Simmons"
                        class="avatar avatar-sm pull-up">

                      <%= image_tag 'portrait/small/avatar-s-8.png', class: 'media-object rounded-circle', alt: 'Avatar' %>
                    </li>
                    <li data-toggle="tooltip" data-popup="tooltip-custom" data-original-title="Willie Torres"
                        class="avatar avatar-sm pull-up">

                      <%= image_tag 'portrait/small/avatar-s-7.png', class: 'media-object rounded-circle', alt: 'Avatar' %>
                    </li>
                    <li data-toggle="tooltip" data-popup="tooltip-custom" data-original-title="Rebecca Jones"
                        class="avatar avatar-sm pull-up">

                      <%= image_tag 'portrait/small/avatar-s-6.png', class: 'media-object rounded-circle', alt: 'Avatar' %>
                    </li>
                    <li class="avatar avatar-sm">
                      <span class="badge badge-info">+1 more</span>
                    </li>
                  </ul>
                </td>
                <td class="text-truncate">$8500</td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--/ Products sell and New Orders -->

app/views/static_pages/dashboard.html.erb
<div class="app-content content">
  <div class="content-wrapper">
    <div class="content-header row">
    </div>
    <%= render 'shared/left_main_menu' %>
    <div class="content-body">
      <%= render 'ecommerce_statistics' %>
      <%= render 'product_sell_info' %>
      <%= render 'recent_transactions' %>
      <%= render 'recent_orders_sales' %>
      <%= render 'horizontal_timeline' %>
    </div>
  </div>
</div>
<!-- ////////////////////////////////////////////////////////////////////////////-->